"""Совместимый re-export слой для `from web_portal.lib.db import …`.

Реализация — в доменных модулях; здесь только агрегирующий импорт.
"""
from __future__ import annotations

from web_portal.lib.db.network_intensity import (  # noqa: E402,F401
    _date_only_window,
    _dt_time_part,
    _finalize_intensity_cluster_map,
    _is_calendar_day_end,
    _is_calendar_day_start,
    _merge_intensity_agg_row,
    _network_prev_daily_window,
    get_network_intensity_clusters,
    get_network_intensity_clusters_dual,
    get_network_intensity_clusters_dual_daily,
)

from web_portal.lib.db.analysis_data import (  # noqa: E402,F401
    _format_duty_codes,
    _parse_duty_codes,
    get_analysis_assignments,
    list_analysis_assignments_since,
    set_analysis_assignment,
)

from web_portal.lib.db.asr import (  # noqa: E402,F401
    activate_asr_model,
    add_asr_feedback,
    add_asr_train_sample,
    count_asr_feedback,
    create_asr_training_run,
    finish_asr_training_run,
    get_active_asr_model,
    get_asr_settings,
    list_asr_models,
    list_asr_train_samples,
    set_asr_settings,
    upsert_asr_model,
)

from web_portal.lib.db.map_shared import (  # noqa: E402,F401
    get_map_shared_objects,
    get_map_shared_objects_all,
    save_map_shared_objects,
)

from web_portal.lib.db.ai import add_ai_feedback

from web_portal.lib.db.sql_util import (  # noqa: E402,F401
    _in_clause,
    _normalize_positions,
    _pick_first,
    _table_columns,
)

from web_portal.lib.db.intercepts import (  # noqa: E402,F401
    _archive_closed_intercept_sessions,
    _extract_last_time_block,
    _get_last_recorded_intercept_by_freq_group,
    _intercept_session_base_min,
    _migrate_intercept_audio_listened,
    _migrate_intercept_audio_tasks,
    _migrate_intercept_blocks_backfill,
    _migrate_intercept_callsigns,
    _migrate_intercepts_sync_fields,
    _os_norm_freq,
    _sync_intercept_item_blocks_unsafe,
    add_intercept_audio_task,
    apply_intercept_catalog_delete_from_sync,
    close_active_and_start_new_intercept_session,
    compute_intercept_word_delta,
    delete_intercept_audio_task,
    delete_intercept_callsign,
    delete_intercept_catalog,
    get_intercept_audio_state,
    get_intercept_audio_transcript,
    get_intercept_item_sync_payload,
    get_intercept_session,
    get_intercept_txt_push_state,
    get_intercept_word_push_state,
    get_or_create_active_intercept_session,
    get_or_create_intercept_item,
    init_intercepts,
    is_intercept_session_closed,
    list_intercept_audio_listened_keys,
    list_intercept_audio_tasks,
    list_intercept_callsigns,
    list_intercept_callsigns_for_unit_pair,
    list_intercept_callsigns_since,
    list_intercept_catalog,
    list_intercept_catalog_deletes_since,
    list_intercept_catalog_since,
    list_intercept_item_blocks,
    list_intercept_items_for_day,
    list_intercept_items_for_session,
    list_intercept_items_since,
    list_intercept_sessions,
    list_intercept_sessions_ordered,
    list_intercept_sessions_since,
    mark_intercept_audio_listened,
    merge_intercept_day_contents,
    record_intercept_catalog_delete,
    replace_intercept_item_content,
    search_intercept_items,
    set_intercept_audio_task_active,
    set_intercept_txt_push_state,
    set_intercept_word_push_state,
    sync_intercept_item_blocks,
    update_intercept_callsign_label,
    update_intercept_callsign_tag,
    update_intercept_item_content,
    upsert_intercept_audio_state,
    upsert_intercept_audio_transcript,
    upsert_intercept_callsign,
    upsert_intercept_callsign_from_sync,
    upsert_intercept_catalog,
    upsert_intercept_catalog_from_sync,
    upsert_intercept_item_from_sync,
    upsert_intercept_session_from_sync,
)

from web_portal.lib.db.online_search import (  # noqa: E402,F401
    _child_label_sort,
    _ensure_online_search_unit_profile,
    _parent_merge_key,
    _row_to_online_search_dict,
    count_online_search_by_unit_key,
    delete_online_search_row,
    get_online_search_headers,
    get_online_search_meta,
    get_online_search_meta_payload,
    get_online_search_unit_profile,
    init_online_search,
    list_archive_freq_by_note,
    list_distinct_online_search_units,
    list_online_search,
    list_online_search_ids_for_note_pair,
    list_online_search_rows_after,
    list_online_search_rows_by_unit_key,
    list_online_search_unit_avatar_files,
    list_online_search_unit_families,
    merge_families_by_manual_groups,
    set_online_search_headers,
    set_online_search_unit_avatar,
    set_online_search_unit_profile,
    sync_units_from_online_search,
    update_online_search_note,
    upsert_online_search_meta_from_sync,
    upsert_online_search_row,
    upsert_online_search_rows_from_sync,
    upsert_online_search_unit_profile,
)

from web_portal.lib.db.units import (  # noqa: E402,F401
    _build_unit_name_map_for_pairs,
    _extract_gid_tokens,
    _get_unit_name_for_pair,
    _is_unknown_intensity_unit_name,
    _norm_unit_note,
    _normalize_frequency_key,
    _normalize_group_text,
    _sql_freq_zone_expr,
    _try_loose_child_prefix,
    _unit_map,
    _unit_map_legacy,
    _unit_parent_groups_file,
    _unit_row_score,
    add_sessions_favorite,
    apply_search_note_to_unit,
    build_sessions_favorite_match_set,
    canonical_intensity_unit_key,
    freq_zone_for_sessions_merge,
    get_pairs_for_unit_name,
    get_sessions_favorites,
    get_unit_family_by_parent_key,
    list_dict_callsigns,
    list_dict_frequencies,
    list_dict_units,
    list_unit_rows_after_rowid,
    list_unit_rows_since,
    list_units_tree,
    load_unit_parent_manual_groups,
    match_callsign_for_corr,
    parse_note_unit_parent_child,
    remove_sessions_favorite,
    sessions_favorite_matches_row,
    sessions_row_is_favorite,
    update_unit_name,
)

from web_portal.lib.db.seans_query import (  # noqa: E402,F401
    _get_last_recorded_by_freq_group,
    count_seanses_by_code,
    count_seanses_by_code_for_unit,
    get_seanses_rows_export,
    list_active_seans_freq_groups_for_unit_name,
    list_distinct_seans_frequency_groups,
    list_seans_pairs,
    list_seanses_ids_for_unit_pair,
    list_seanses_rows_after_rowid,
    list_seanses_since,
    seanses_datetime_extremes_for_unit_pair,
    upsert_seanses_rows_from_sync,
)

from web_portal.lib.db.seans_write import (  # noqa: E402,F401
    _delete_conflicting_tt_seans_rows,
    _parse_seans_date_time_value,
    _processed_files_key,
    _save_seans_batch,
    _save_seans_batch_with_client,
    import_folder,
    import_folder_incremental,
    import_folder_with_client,
    mark_processed,
    max_seans_date_times_by_frequency,
    save_all_from_dir,
    save_seans_entries,
    scan_seanses_once,
    seans_entries_fully_in_database,
    was_processed,
)

from web_portal.lib.db.seans_archive import (  # noqa: E402,F401
    archive_all_seanses_to_archive,
    archive_seanses_before_date_to_file,
    archive_seanses_outside_current_day,
    cleanup_seanses,
    clear_seanses_by_client_name,
    init_seanses_archive_file_schema,
    resolve_seans_conn_for_queries,
)

from web_portal.lib.db.stats import (  # noqa: E402,F401
    _daily_agg_network_pairs_for_days,
    _daily_agg_sessions_total_for_days,
    _doc_stats_page_build_result,
    _doc_stats_page_grouped_sql,
    _doc_stats_page_ids_from_daily_agg,
    _doc_stats_page_ids_from_daily_agg_chunk,
    _doc_stats_page_ids_map,
    _doc_stats_page_ids_map_chunk,
    _seans_network_pairs_for_days,
    _seans_sessions_total_for_days,
    _seanses_period_has_rows,
    _try_get_doc_stats_page_from_daily_agg,
    dump_selected_rows_for_doc,
    format_ids,
    get_db_stats,
    get_db_stats_legacy,
    get_doc_stats,
    get_doc_stats_legacy,
    get_doc_stats_page,
)

from web_portal.lib.db.seans_schema import (  # noqa: E402,F401
    _table_exists,
    init_daily_aggregates,
    init_seans_tables,
    refresh_seanses_daily_aggregates,
    refresh_seanses_daily_aggregates_for_entries,
    seanses_union_source_sql,
)

from web_portal.lib.db.connection import (  # noqa: E402,F401
    _CONN_DEFER_COMMIT_IDS,
    _CONN_DEFER_COMMIT_LOCK,
    _CONN_INIT_IDS,
    _CONN_SCHEMA_KEYS_BY_ID,
    _SCHEMA_READY_PATHS,
    _commit_if_needed,
    _conn_has_core_schema,
    _conn_has_table,
    _conn_schema_key,
    _schema_ready_for_conn,
    _sqlite_optimize_once_done,
    _sqlite_optimize_once_lock,
    connect,
    connection_defer_commit_active,
    ensure_db,
    finish_connection_defer_commit,
    init_db,
    list_db_files,
    optimize_connection,
    set_connection_defer_commit,
    unregister_connection,
)

from web_portal.lib.db.sync import (  # noqa: E402,F401
    _SYNC_OUTBOX_PRIORITY_KINDS,
    _sync_blocks_quietly,
    _sync_outbox_priority_order_sql,
    enqueue_sync_outbox,
    get_sync_meta,
    init_sync,
    list_sync_outbox_pending,
    mark_sync_outbox_failed,
    mark_sync_outbox_sent,
    set_sync_meta,
    upsert_analysis_assignment_from_sync,
    upsert_unit_rows_from_sync,
)

from web_portal.lib.db.ai import (  # noqa: E402,F401
    create_ai_job,
    create_ai_report,
    get_ai_job,
    init_ai_tables,
    list_ai_reports,
    update_ai_job,
)
